### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by divergencetech** [divergencetech/ethier#13]
Needs:

- [x] Run tests
- [x] Linter against `gofmt` for Go and `prettier` for Solidity
- [ ] Required to pass before commits / PR merges

I have very little experience with GitHub so would appreciate help please if anyone already knows how to do this so I don't have to start digging around :)

**Comment by cxkoda** [comment]
I think the last point is something that you have to set in the repository settings.

**Comment by aschlosberg** [comment]
Thank you. I'm gonna mark as fixed because it achieves what we need for now. I'll look into branch protection to enforce things at another time
