### ISSUE TITLE
After _msgSender change in ERC721A, contracts are no longer compiling

### ISSUE THREAD

**Issue by ian** [divergencetech/ethier#33]
```
> hardhat compile && tsc

DeclarationError: Undeclared identifier.
  --> @divergencetech/ethier/contracts/erc721/ERC721APreApproval.sol:55:25:
   |
55 |         address owner = _msgSender();
   |                         ^^^^^^^^^^


Error HH600: Compilation failed
```

Seems about 20 days ago they introduced a breaking change to the method signature: https://github.com/chiru-labs/ERC721A/pull/280

Fix is to rename `_msgSender` to `_erc721aMsgSender`

**Comment by GIPPERMORF** [comment]
changed and updated but still same error through yarn compilation
